version: '3'
services:
  # web:
  #   build:
  #     context: ./didauday-web
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /app/node_modules
  #     - ./didauday-web:/app
  #   restart: always
  # dashboard:
  #   build:
  #     context: ./didauday-dashboard
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - /app/node_modules
  #     - ./didauday-dashboard:/app
  #   restart: always
  tour:
    build:
      context: ./didauday-server/services/tour
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - /app/node_modules
      - ./didauday-server/services/tour:/app
    depends_on:
      - mongo
      - neo4j
      - redis
    environment:
      - PORT=5001
      - NEO4J_PROTOCOL=bolt
      - NEO4J_HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=annq
      - NEO4J_PORT=7687
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=didauday
    restart: always
  user:
    build:
      context: ./didauday-server/services/user
      dockerfile: Dockerfile.dev
    ports:
      - "5002:5002"
    volumes:
      - /app/node_modules
      - ./didauday-server/services/user:/app
    depends_on:
      - mongo
      - neo4j
      - redis
      - prisma-server
      - prisma
    environment:
      - PORT=5002
      - NEO4J_PROTOCOL=bolt
      - NEO4J_HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=annq
      - NEO4J_PORT=7687
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=didauday
      - PRISMA_URL=http://prisma:4466
      - PRISMA_SCHEMA_URL=http://prisma-server:4444/schema/prisma.graphql
    restart: always
  flight:
    build:
      context: ./didauday-server/services/flight
      dockerfile: Dockerfile.dev
    ports:
      - "5003:5003"
    volumes:
      - /app/node_modules
      - ./didauday-server/services/flight:/app
    depends_on:
      - mongo
      - neo4j
      - redis
    environment:
      - PORT=5003
      - NEO4J_PROTOCOL=bolt
      - NEO4J_HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=annq
      - NEO4J_PORT=7687
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=didauday
    restart: always  
  move-data:
    build:
      context: ./didauday-server/services/move-data
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./didauday-server/services/move-data:/app
    depends_on:
      - mongo
      - neo4j
    environment:
      - NEO4J_PROTOCOL=bolt
      - NEO4J_HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=annq
      - NEO4J_PORT=7687
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=didauday
    restart: always
  crawl-data:
    build:
      context: ./didauday-server/services/crawl-data
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./didauday-server/services/crawl-data:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=didauday
    restart: always
  place:
    build:
      context: ./didauday-server/services/place
      dockerfile: Dockerfile.dev
    ports:
      - "5004:5004"
    volumes:
      - /app/node_modules
      - ./didauday-server/services/place:/app
    depends_on:
      - mongo
      - neo4j
      - redis
    environment:
      - PORT=5004
      - NEO4J_PROTOCOL=bolt
      - NEO4J_HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=annq
      - NEO4J_PORT=7687
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=didauday
    restart: always
  hotel:
    build:
      context: ./didauday-server/services/hotel
      dockerfile: Dockerfile.dev
    ports:
      - "5005:5005"
    volumes:
      - /app/node_modules
      - ./didauday-server/services/hotel:/app
    depends_on:
      - mongo
      - neo4j
      - redis
    environment:
      - PORT=5005
      - NEO4J_PROTOCOL=bolt
      - NEO4J_HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=annq
      - NEO4J_PORT=7687
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=didauday
    restart: always
  review:
    build:
      context: ./didauday-server/services/review
      dockerfile: Dockerfile.dev
    ports:
      - "5006:5006"
    volumes:
      - /app/node_modules
      - ./didauday-server/services/review:/app
    depends_on:
      - mongo
      - neo4j
      - redis
    environment:
      - PORT=5006
      - NEO4J_PROTOCOL=bolt
      - NEO4J_HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=annq
      - NEO4J_PORT=7687
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=didauday
    restart: always
  favorite:
    build:
      context: ./didauday-server/services/favorite
      dockerfile: Dockerfile.dev
    ports:
      - "5007:5007"
    volumes:
      - /app/node_modules
      - ./didauday-server/services/favorite:/app
    depends_on:
      - mongo
      - neo4j
      - redis
    environment:
      - PORT=5007
      - NEO4J_PROTOCOL=bolt
      - NEO4J_HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=annq
      - NEO4J_PORT=7687
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=didauday
    restart: always
  discount:
    build:
      context: ./didauday-server/services/discount
      dockerfile: Dockerfile.dev
    ports:
      - "5008:5008"
    volumes:
      - /app/node_modules
      - ./didauday-server/services/discount:/app
    depends_on:
      - mongo
      - neo4j
      - redis
    environment:
      - PORT=5008
      - NEO4J_PROTOCOL=bolt
      - NEO4J_HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=annq
      - NEO4J_PORT=7687
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=didauday
    restart: always
  booking:
    build:
      context: ./didauday-server/services/booking
      dockerfile: Dockerfile.dev
    ports:
      - "5009:5009"
    volumes:
      - /app/node_modules
      - ./didauday-server/services/booking:/app
    depends_on:
      - mongo
      - neo4j
      - redis
    environment:
      - PORT=5009
      - NEO4J_PROTOCOL=bolt
      - NEO4J_HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=annq
      - NEO4J_PORT=7687
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=didauday
    restart: always
  prisma-server:
    build:
      context: ./didauday-server/services/prisma
      dockerfile: Dockerfile.dev
    ports:
      - "4444:4444"
    volumes:
      - /app/node_modules
      - ./didauday-server/services/prisma:/app
    depends_on:
      - prisma
  server:
    build:
      context: ./didauday-server/gateway
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./didauday-server/gateway:/app
    depends_on:
      - tour
      - user
      - flight
      - place
      - hotel
      - review
      - favorite
      - discount
      - booking
    environment:
      - TOUR_URL=http://tour:5001/graphql
      - USER_URL=http://user:5002/graphql
      - FLIGHT_URL=http://flight:5003/graphql
      - PLACE_URL=http://place:5004/graphql
      - HOTEL_URL=http://hotel:5005/graphql
      - REVIEW_URL=http://review:5006/graphql
      - FAVORITE_URL=http://favorite:5007/graphql
      - DISCOUNT_URL=http://discount:5008/graphql
      - BOOKING_URL=http://booking:5009/graphql
      - PORT=5000
    restart: always
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    depends_on:
      - mongo
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://mongo:27017
            database: didauday
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./databases/mongo/db:/data/db
    restart: always
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./databases/neo4j/db:/data/db
    environment:
      - NEO4J_AUTH=neo4j/annq
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./databases/redis/db:/data/db
    restart: always