version: '3'
services:
  web:
    build:
      context: ./didauday-web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./didauday-web:/app
    restart: always
  dashboard:
    build:
      context: ./didauday-dashboard
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./didauday-dashboard:/app
    restart: always
  tour:
    build:
      context: ./didauday-server/services/tour
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - /app/node_modules
      - ./didauday-server/services/tour:/app
    environment:
      - PORT=5001
    restart: always
  auth:
    build:
      context: ./didauday-server/services/auth
      dockerfile: Dockerfile.dev
    ports:
      - "5002:5002"
    volumes:
      - /app/node_modules
      - ./didauday-server/services/auth:/app
    environment:
      - PORT=5002
    restart: always
  server:
    build:
      context: ./didauday-server/gateway
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./didauday-server/gateway:/app
    depends_on:
      - tour
      - auth
    environment:
      - TOUR_URL=http://tour:5001/graphql
      - AUTH_URL=http://auth:5002/graphql
      - PORT=5000
    restart: always
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./databases/mongo/db:/data/db
    restart: always
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./databases/neo4j/db:/data/db
    environment:
      - NEO4J_AUTH=neo4j/annq
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./databases/redis/db:/data/db
    restart: always