# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiDauDayApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DiDauDayApp

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'DiDauDayAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DiDauDayApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DiDauDayApp-tvOS

  target 'DiDauDayApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
