version: '3'
services:
  tour:
    build:
      context: ./services/tours
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - /app/node_nodules
      - ./services/tours:/app
    restart: always
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_nodules
      - ./gateway:/app
    depends_on:
      - "tour"
    environment:
      - POST_URL=http://tour:5001/graphql
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./databases/mongo/db:/data/db
    restart: always
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./databases/neo4j/db:/data/db
    environment:
      - NEO4J_AUTH=neo4j/annq
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./databases/redis/db:/data/db
    restart: always