FROM node:alpine

WORKDIR /app

# install prisma cli
RUN npm install -g prisma

COPY . .

# allow execution for entrypoint scripts
# USER ROOT
# CMD ["chmod", "+x" ,"/app/entrypoint.sh"]

ENTRYPOINT ["/bin/sh", "./entrypoint.sh"]